### ISSUE TITLE
Crash Duplicate IDs

### ISSUE THREAD

**Issue by hero887** [cyanobacterium/SteamAdvantage#5]
If needed I can supply more. But it seemed it was just the duplicate IDs causing the problem.

[13:15:30] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[13:15:30] [Client thread/ERROR] [FML]: Caught exception from steamadvantage
java.lang.IllegalArgumentException: Duplicate enchantment id! class cyano.steamadvantage.enchanments.PowderlessEnchantment and class cyano.steamadvantage.enchanments.RapidReloadEnchantment Enchantment ID:9

**Comment by hero887** [comment]
For safe measure I included the full report...It crashes for the 1.3.5 ver. as well as the 1.4.0 ver. of Steam Adv.

[13:24:05] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[13:24:05] [Client thread/ERROR] [FML]: Caught exception from steamadvantage
java.lang.IllegalArgumentException: Duplicate enchantment id! class cyano.steamadvantage.enchanments.PowderlessEnchantment and class cyano.steamadvantage.enchanments.RapidReloadEnchantment Enchantment ID:9
    at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:65) ~[apf.class:?]
    at cyano.steamadvantage.enchanments.PowderlessEnchantment.<init>(PowderlessEnchantment.java:13) ~[PowderlessEnchantment.class:?]
    at cyano.steamadvantage.init.Enchantments.init(Enchantments.java:19) ~[Enchantments.class:?]
    at cyano.steamadvantage.SteamAdvantage.init(SteamAdvantage.java:99) ~[SteamAdvantage.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553) ~[forge-1.8-11.14.4.1563-universal.jar:?]
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.8-11.14.4.1563-universal.jar:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.8-11.14.4.1563-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731) [Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Unknown Source) [bsu.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bsu.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[13:24:05] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.crash.CrashReportCategory.func_85069_a(CrashReportCategory.java:146) ~[j.class:?]
    at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:320) ~[b.class:?]
    at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:290) ~[b.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) ~[bsu.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:120) ~[Main.class:?]
    ... 14 more
[13:24:05] [Client thread/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:313]: Failed to start Minecraft:
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.reflect.Method.invoke(Method.java:497)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at org.multimc.EntryPoint.main(EntryPoint.java:54)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Runtime.exit(Runtime.java:107)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.System.exit(System.java:971)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     ... 8 more
[13:24:05] [Client thread/INFO] [STDOUT]: [org.multimc.EntryPoint:main:57]: Exiting with -1
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 5
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Runtime.exit(Runtime.java:107)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.System.exit(System.java:971)
[13:24:05] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at org.multimc.EntryPoint.main(EntryPoint.java:58)

**Comment by DrPlantabyte** [comment]
That's strange, as I explicitly check for duplicate IDs to avoid exactly this error. I'll look into it later today.

**Comment by hero887** [comment]
No prob. I can say that I have a large number of mods included with yours. See full list here if needed: https://docs.google.com/spreadsheets/d/1K-kE5cldIXRrtn64UslmKIX3uzUn_YL9gsN6nHSPQlI/edit?usp=sharing

I was able to get it running as soon as I removed the "More Enchants" mod. I guessed it could have been an issue with yours. It ran for me now. It's working.

**Comment by DrPlantabyte** [comment]
Well, I would like to be compatible with the More Enchants mod, so if you could provide me with a link to their mod website and source code (if available), I would really appreciate it.

**Comment by hero887** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1445082-more-enchantments-version-1-3-now-for-1-8

https://github.com/Lithial

**Comment by DrPlantabyte** [comment]
I just remembered that someone had the same problem a long time ago. It turned out that the enchantments mod had a config option to change the max number of enchantments and it defaulted to 100, whereas Minecraft originally had space for 256. Try increasing the limit up to 256 and see if that fixes it.
